version: "2"
services:
  db:
    image: postgres
  django:
    build: .
    command: python3 hearstbook/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  migrate:
    build: .
    command: python3 hearstbook/manage.py migrate
